# Demo v13 dataclasses

In [1]:
import py4DSTEM
import numpy as np

In [2]:
py4DSTEM.__version__

'0.13.0'

## Array

In [3]:
py4DSTEM.io.datastructure.Array?

In [4]:
# Make an array

shape = (3,4,5,6,7)
data = np.arange(np.prod(shape)).reshape(shape)

py4dstem_array = py4DSTEM.io.datastructure.Array(
    data = data,
    name = 'test_array',
    units = 'intensity',   # units of the data elements, rather than the dims
    dims = [
        5,              # dims can be a single number, then a leading '0' is assumed
        [0,5],          # they can be a pair of numbers, then Array linearly extrapolates
        0.1243,
        [0,2,3,4,5,10]  # or they can be a vector of the appropriate length
                        # any unspecified dims are autopopulated as [0,1,...]
    ],
    dim_units = [
        'nm',           # any dims with unspecified units will be autopopulated with
        'nm',           # either "pixels" (if the dim was set to [0,1,..]) or "unknown" (if not)
        'A^-1',
    ],
    dim_names = [
        'rx',
        'ry',
        'qx',
    ]
)

In [5]:
py4dstem_array

Array( A 5-dimensional array of shape (3, 4, 5, 6, 7) called 'test_array',
       with dimensions:

       rx = [0,5,...] nm
       ry = [0,5,...] nm
       qx = [0.0,0.1243,...] A^-1
       dim3 = [0,2,...] unknown
       dim4 = [0,1,...] pixels
)

In [6]:
print(py4dstem_array.shape)
print(py4dstem_array.rank)

(3, 4, 5, 6, 7)
5


In [9]:
py4dstem_array.data[:2,:2,:2,:2,:2]

array([[[[[   0,    1],
          [   7,    8]],

         [[  42,   43],
          [  49,   50]]],


        [[[ 210,  211],
          [ 217,  218]],

         [[ 252,  253],
          [ 259,  260]]]],



       [[[[ 840,  841],
          [ 847,  848]],

         [[ 882,  883],
          [ 889,  890]]],


        [[[1050, 1051],
          [1057, 1058]],

         [[1092, 1093],
          [1099, 1100]]]]])

In [10]:
py4dstem_array[:2,:2,:2,:2,:2]

array([[[[[   0,    1],
          [   7,    8]],

         [[  42,   43],
          [  49,   50]]],


        [[[ 210,  211],
          [ 217,  218]],

         [[ 252,  253],
          [ 259,  260]]]],



       [[[[ 840,  841],
          [ 847,  848]],

         [[ 882,  883],
          [ 889,  890]]],


        [[[1050, 1051],
          [1057, 1058]],

         [[1092, 1093],
          [1099, 1100]]]]])

In [11]:
# Make an array stack

# Make a 3D numpy array
shape = (10,10,4)
data = np.arange(np.prod(shape)).reshape(shape)

# Make the Array instance
py4dstem_arraystack = py4DSTEM.io.datastructure.Array(
    data = data,
    name = 'test_arraystack',
    units = 'intensity',
    dims = [
        5,
        [0,5]
    ],
    dim_units = [
        'nm',
        'nm'
    ],
    dim_names = [
        'rx',
        'ry'
    ],
    slicelabels = [             # to make a stack array, just pass 'slicelabels', and the last dim
        'the',                  # is understood to be the slice axis
        'cow',
        'jumped',
        'over'
    ]
)

In [13]:
py4dstem_arraystack

Array( A stack of 4 Arrays with 2-dimensions and shape (10, 10), called 'test_arraystack'

       The labels are:
           the
           cow
           jumped
           over


       The Array dimensions are:
           rx = [0,5,...] nm
           ry = [0,5,...] nm
)

In [14]:
print(py4dstem_arraystack.shape)
print(py4dstem_arraystack.rank)

(10, 10)
2


In [15]:
print(py4dstem_arraystack.data.shape)
print(py4dstem_arraystack.depth)

(10, 10, 4)
4


In [17]:
print(py4dstem_arraystack.data.ndim)

3


In [18]:
print(py4dstem_array.depth)

0


In [21]:
py4dstem_arraystack.get_slice('cow')

Array( A 2-dimensional array of shape (10, 10) called 'test_arraystack_cow',
       with dimensions:

       rx = [0,5,...] nm
       dim1 = [0,1,...] pixels
)

In [22]:
py4dstem_arraystack['cow']

Array( A 2-dimensional array of shape (10, 10) called 'test_arraystack_cow',
       with dimensions:

       rx = [0,5,...] nm
       dim1 = [0,1,...] pixels
)

In [23]:
py4dstem_arraystack.slicelabels

['the', 'cow', 'jumped', 'over']

In [24]:
# Re-assigning a slice name propagates correctly
py4dstem_arraystack.slicelabels[2] = 'meow'

In [25]:
py4dstem_arraystack.slicelabels

['the', 'cow', 'meow', 'over']

In [26]:
py4dstem_arraystack

Array( A stack of 4 Arrays with 2-dimensions and shape (10, 10), called 'test_arraystack'

       The labels are:
           the
           cow
           meow
           over


       The Array dimensions are:
           rx = [0,5,...] nm
           ry = [0,5,...] nm
)

In [28]:
py4dstem_arraystack['meow']

Array( A 2-dimensional array of shape (10, 10) called 'test_arraystack_meow',
       with dimensions:

       rx = [0,5,...] nm
       dim1 = [0,1,...] pixels
)

In [29]:
py4dstem_arraystack.get_slice('meow', name='meowth_thats_right')

Array( A 2-dimensional array of shape (10, 10) called 'meowth_thats_right',
       with dimensions:

       rx = [0,5,...] nm
       dim1 = [0,1,...] pixels
)

In [30]:
py4dstem_arraystack['cow',3,4]

137

In [31]:
py4dstem_arraystack['cow',3:5,4:7]

array([[137, 141, 145],
       [177, 181, 185]])

In [32]:
py4dstem_arraystack[3:5,4:7,1]

array([[137, 141, 145],
       [177, 181, 185]])

## Datacube

(child class of Array)

In [36]:
# Make a 4D datacube

shape = (8,8,64,64)
data = np.ones(shape)

datacube = py4DSTEM.io.datastructure.DataCube(
    data = data,
    name = 'test_datacube',
    rsize = 5,                      # rsize,qsize,runits,qunits can all be either a len-2 list
    runits = 'nm',                  # or a number, which will autopopulate a len-2 list
    qsize = [0.01,0.02],
    qunits = ['A^-1','nm^-1']
)

In [37]:
datacube

DataCube( A 4-dimensional array of shape (8, 8, 64, 64) called 'test_datacube',
          with dimensions:

          Rx = [0,5,...] nm
          Ry = [0,5,...] nm
          Qx = [0.0,0.01,...] A^-1
          Qy = [0.0,0.02,...] nm^-1
)

In [38]:
datacube.qunits = 'A^-1'
print(datacube.qunits)
print(datacube.dim_units)
print()
datacube

['A^-1', 'A^-1']
['nm', 'nm', 'A^-1', 'A^-1']



DataCube( A 4-dimensional array of shape (8, 8, 64, 64) called 'test_datacube',
          with dimensions:

          Rx = [0,5,...] nm
          Ry = [0,5,...] nm
          Qx = [0.0,0.01,...] A^-1
          Qy = [0.0,0.02,...] A^-1
)

In [39]:
# Make a stack of 4D datacubes

shape = (8,8,64,64,3)
data = np.ones(shape)

datacubestack = py4DSTEM.io.datastructure.DataCube(
    data = data,
    name = 'test_datacubestack',
    rsize = 5,
    runits = 'nm',
    qsize = [0.01,0.02],
    qunits = ['A^-1','nm^-1'],
    slicelabels = [
        'datacube1',
        'datacube2',
        'datacube3'
    ]
)

In [40]:
datacubestack

DataCube( A stack of 3 Arrays with 4-dimensions and shape (8, 8, 64, 64), called 'test_datacubestack'

          The labels are:
              datacube1
              datacube2
              datacube3


          The Array dimensions are:
              Rx = [0,5,...] nm
              Ry = [0,5,...] nm
              Qx = [0.0,0.01,...] A^-1
              Qy = [0.0,0.02,...] nm^-1
)

In [41]:
datacubestack.qunits = 'A^-1'
print(datacubestack.qunits)
print(datacubestack.dim_units)
print(datacubestack)

['A^-1', 'A^-1']
['nm', 'nm', 'A^-1', 'A^-1']
DataCube( A stack of 3 Arrays with 4-dimensions and shape (8, 8, 64, 64), called 'test_datacubestack'

          The labels are:
              datacube1
              datacube2
              datacube3


          The Array dimensions are:
              Rx = [0,5,...] nm
              Ry = [0,5,...] nm
              Qx = [0.0,0.01,...] A^-1
              Qy = [0.0,0.02,...] A^-1
)


## DiffractionSlice, RealSlice

(child classes of Array)

In [42]:
# Make a DiffractionSlice

shape = (256,256)
data = np.arange(np.prod(shape)).reshape(shape)

# Make the Array instance
py4dstem_diffractionslice = py4DSTEM.io.datastructure.DiffractionSlice(
    data = data,
    name = 'test_diffractionslice',
    pixelsize = 2,                          # number or len-2 list
    pixelunits = 'A^-1',                    # string or len-2 list
)

In [43]:
py4dstem_diffractionslice

DiffractionSlice( A 2-dimensional array of shape (256, 256) called 'test_diffractionslice',
                  with dimensions:

                  Qx = [0,2,...] A^-1
                  Qy = [0,2,...] A^-1
)

In [44]:
# Make a DiffractionSlice stack

shape = (64,64,3)
data = np.ones(shape)

diffractionstack = py4DSTEM.io.datastructure.DiffractionSlice(
    data = data,
    name = 'test_diffractionstack',
    pixelsize = 3,
    pixelunits = 'A^-1',
    slicelabels = [
        'im',
        'a',
        'teapot'
    ]
)

In [45]:
diffractionstack

DiffractionSlice( A stack of 3 Arrays with 2-dimensions and shape (64, 64), called 'test_diffractionstack'

                  The labels are:
                      im
                      a
                      teapot


                  The Array dimensions are:
                      Qx = [0,3,...] A^-1
                      Qy = [0,3,...] A^-1
)

In [46]:
print(diffractionstack.pixelunits)
print(diffractionstack.dim_units)
print(diffractionstack)

['A^-1', 'A^-1']
['A^-1', 'A^-1']
DiffractionSlice( A stack of 3 Arrays with 2-dimensions and shape (64, 64), called 'test_diffractionstack'

                  The labels are:
                      im
                      a
                      teapot


                  The Array dimensions are:
                      Qx = [0,3,...] A^-1
                      Qy = [0,3,...] A^-1
)


## PointList

In [48]:
# Make a PointList

# generate a structured numpy array
dtype = [('qx',float),
         ('qy',float),
         ('I',float),
         ('h',int),
         ('k',int),
         ('l',int)]
data = np.zeros(10,dtype=dtype)

pointlist = py4DSTEM.io.datastructure.PointList(
    data = data,                                     # accepts numpy structured arrays - no more "coordinates"
    name = 'test_pointlist'
)

In [49]:
pointlist

PointList( A length 10 PointList called 'test_pointlist',
           with 6 fields:

           qx   (float64)
           qy   (float64)
           I    (float64)
           h    (int64)
           k    (int64)
           l    (int64)
)

In [50]:
pointlist.data

array([(0., 0., 0., 0, 0, 0), (0., 0., 0., 0, 0, 0),
       (0., 0., 0., 0, 0, 0), (0., 0., 0., 0, 0, 0),
       (0., 0., 0., 0, 0, 0), (0., 0., 0., 0, 0, 0),
       (0., 0., 0., 0, 0, 0), (0., 0., 0., 0, 0, 0),
       (0., 0., 0., 0, 0, 0), (0., 0., 0., 0, 0, 0)],
      dtype=[('qx', '<f8'), ('qy', '<f8'), ('I', '<f8'), ('h', '<i8'), ('k', '<i8'), ('l', '<i8')])

In [51]:
pointlist.data['qx']

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
pointlist.data[:3]

array([(0., 0., 0., 0, 0, 0), (0., 0., 0., 0, 0, 0),
       (0., 0., 0., 0, 0, 0)],
      dtype=[('qx', '<f8'), ('qy', '<f8'), ('I', '<f8'), ('h', '<i8'), ('k', '<i8'), ('l', '<i8')])

In [53]:
pointlist[...]

array([(0., 0., 0., 0, 0, 0), (0., 0., 0., 0, 0, 0),
       (0., 0., 0., 0, 0, 0), (0., 0., 0., 0, 0, 0),
       (0., 0., 0., 0, 0, 0), (0., 0., 0., 0, 0, 0),
       (0., 0., 0., 0, 0, 0), (0., 0., 0., 0, 0, 0),
       (0., 0., 0., 0, 0, 0), (0., 0., 0., 0, 0, 0)],
      dtype=[('qx', '<f8'), ('qy', '<f8'), ('I', '<f8'), ('h', '<i8'), ('k', '<i8'), ('l', '<i8')])

In [54]:
pointlist['qx']

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
pointlist[:3]

array([(0., 0., 0., 0, 0, 0), (0., 0., 0., 0, 0, 0),
       (0., 0., 0., 0, 0, 0)],
      dtype=[('qx', '<f8'), ('qy', '<f8'), ('I', '<f8'), ('h', '<i8'), ('k', '<i8'), ('l', '<i8')])

## PointListArray

In [57]:
# Make a PointListArray

# Set up datatype and shape
dtype = [('qx',float),
         ('qy',float),
         ('I',float)]
shape = (20,30)


pla = py4DSTEM.io.datastructure.PointListArray(
    dtype = dtype,
    shape = shape,
    name = 'test_pla'
)

for rx in range(pla.shape[0]):
    for ry in range(pla.shape[1]):
        data = np.ones(10,dtype=dtype)
        data['I'] *= (ry*shape[0]+rx)
        # add the data
        pla[rx,ry].append(data)

In [58]:
pla

PointListArray( A shape (20, 30) PointListArray called 'test_pla',
                with 3 fields:

                qx   (float64)
                qy   (float64)
                I    (float64)
)

In [59]:
pla.get_pointlist(5,1)

PointList( A length 10 PointList called '5,1',
           with 3 fields:

           qx   (float64)
           qy   (float64)
           I    (float64)
)

In [69]:
pla[5,1]

PointList( A length 10 PointList called '5,1',
           with 3 fields:

           qx   (float64)
           qy   (float64)
           I    (float64)
)

In [62]:
pla[5,1][...]

array([(1., 1., 25.), (1., 1., 25.), (1., 1., 25.), (1., 1., 25.),
       (1., 1., 25.), (1., 1., 25.), (1., 1., 25.), (1., 1., 25.),
       (1., 1., 25.), (1., 1., 25.)],
      dtype=[('qx', '<f8'), ('qy', '<f8'), ('I', '<f8')])

In [64]:
pla.get_pointlist(5,1,name='echidnas_r_us')

PointList( A length 10 PointList called 'echidnas_r_us',
           with 3 fields:

           qx   (float64)
           qy   (float64)
           I    (float64)
)

In [65]:
pla[5,1]

PointList( A length 10 PointList called '5,1',
           with 3 fields:

           qx   (float64)
           qy   (float64)
           I    (float64)
)

## Calibration

In [72]:
cal = py4DSTEM.io.datastructure.Calibration(
    (10,10,50,50)     # can optionally be initialized with a datacube shape
)

cal

Calibration( A Calibration metadata instance called 'calibration', containing the following fields:

             Q_pixel_size:    1
             Q_pixel_units:   pixels
             R_pixel_size:    1
             R_pixel_units:   pixels
             R_Nx:            10
             R_Ny:            10
             Q_Nx:            50
             Q_Ny:            50
)

In [73]:
cal.set_Q_pixel_size(0.1)
cal.set_Q_pixel_units('nm^-1')

cal.set_R_pixel_size(0.2)
cal.set_R_pixel_units('A')
                      
cal

Calibration( A Calibration metadata instance called 'calibration', containing the following fields:

             Q_pixel_size:    0.1
             Q_pixel_units:   nm^-1
             R_pixel_size:    0.2
             R_pixel_units:   A
             R_Nx:            10
             R_Ny:            10
             Q_Nx:            50
             Q_Ny:            50
)

In [87]:
origin = np.ones((10,10,2))*5.2
cal.set_origin(origin)

cal

Calibration( A Calibration metadata instance called 'calibration', containing the following fields:

             Q_pixel_size:    0.1
             Q_pixel_units:   nm^-1
             R_pixel_size:    0.2
             R_pixel_units:   A
             R_Nx:            10
             R_Ny:            10
             Q_Nx:            50
             Q_Ny:            50
             origin:          3D-array
             a:               1
             b:               1
             theta:           0
)

In [83]:
cal.get_origin().shape  # flip dims so 2 is first

(10, 10, 2)

In [84]:
cal.get_ellipse(2,5)

(1, 1, 0)

In [77]:
cal.set_ellipse((1,1,0))

In [78]:
cal.get_ellipse()

(1, 1, 0)

In [ ]:
cal.get_p_ellipse()

In [ ]:
# get_ellipticity   
# get_ellipse

# get_elliptical_coordinates